name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  test_build_web:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2 

    - name: Build and Publish 
      uses: VaultVulp/gp-docker-action@1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: dev-env 
        image-tag: latest
